/*
 * generated by Xtext 2.18.0
 */
package nl.wur.inf


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SafetyDSLStandaloneSetup extends SafetyDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new SafetyDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
