/*
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSafetyDSLScopeProvider extends DelegatingScopeProvider {
}
