/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import nl.wur.inf.safetyDSL.CriticalityLevel;
import nl.wur.inf.safetyDSL.SafetyDSLPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Criticality Level</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CriticalityLevelImpl extends MinimalEObjectImpl.Container implements CriticalityLevel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CriticalityLevelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SafetyDSLPackage.Literals.CRITICALITY_LEVEL;
  }

} //CriticalityLevelImpl
