/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import nl.wur.inf.safetyDSL.FaultDetection;
import nl.wur.inf.safetyDSL.SafetyDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fault Detection</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FaultDetectionImpl extends SafetyTacticImpl implements FaultDetection
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FaultDetectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SafetyDSLPackage.Literals.FAULT_DETECTION;
  }

} //FaultDetectionImpl
