/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import java.util.Collection;

import nl.wur.inf.safetyDSL.ReportsFault;
import nl.wur.inf.safetyDSL.SafetyCritical;
import nl.wur.inf.safetyDSL.SafetyDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reports Fault</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.impl.ReportsFaultImpl#getSafetyCritical1 <em>Safety Critical1</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.impl.ReportsFaultImpl#getSafetyCritical2 <em>Safety Critical2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReportsFaultImpl extends SafetyCriticalRelationImpl implements ReportsFault
{
  /**
   * The cached value of the '{@link #getSafetyCritical1() <em>Safety Critical1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSafetyCritical1()
   * @generated
   * @ordered
   */
  protected SafetyCritical safetyCritical1;

  /**
   * The cached value of the '{@link #getSafetyCritical2() <em>Safety Critical2</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSafetyCritical2()
   * @generated
   * @ordered
   */
  protected EList<SafetyCritical> safetyCritical2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReportsFaultImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SafetyDSLPackage.Literals.REPORTS_FAULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyCritical getSafetyCritical1()
  {
    if (safetyCritical1 != null && safetyCritical1.eIsProxy())
    {
      InternalEObject oldSafetyCritical1 = (InternalEObject)safetyCritical1;
      safetyCritical1 = (SafetyCritical)eResolveProxy(oldSafetyCritical1);
      if (safetyCritical1 != oldSafetyCritical1)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL1, oldSafetyCritical1, safetyCritical1));
      }
    }
    return safetyCritical1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SafetyCritical basicGetSafetyCritical1()
  {
    return safetyCritical1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSafetyCritical1(SafetyCritical newSafetyCritical1)
  {
    SafetyCritical oldSafetyCritical1 = safetyCritical1;
    safetyCritical1 = newSafetyCritical1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL1, oldSafetyCritical1, safetyCritical1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SafetyCritical> getSafetyCritical2()
  {
    if (safetyCritical2 == null)
    {
      safetyCritical2 = new EObjectResolvingEList<SafetyCritical>(SafetyCritical.class, this, SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL2);
    }
    return safetyCritical2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL1:
        if (resolve) return getSafetyCritical1();
        return basicGetSafetyCritical1();
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL2:
        return getSafetyCritical2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL1:
        setSafetyCritical1((SafetyCritical)newValue);
        return;
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL2:
        getSafetyCritical2().clear();
        getSafetyCritical2().addAll((Collection<? extends SafetyCritical>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL1:
        setSafetyCritical1((SafetyCritical)null);
        return;
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL2:
        getSafetyCritical2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL1:
        return safetyCritical1 != null;
      case SafetyDSLPackage.REPORTS_FAULT__SAFETY_CRITICAL2:
        return safetyCritical2 != null && !safetyCritical2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ReportsFaultImpl
