/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import java.util.Collection;

import nl.wur.inf.safetyDSL.SafetyDSLPackage;
import nl.wur.inf.safetyDSL.SafetyTactic;
import nl.wur.inf.safetyDSL.SafetyTacticViewpoint;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Safety Tactic Viewpoint</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.impl.SafetyTacticViewpointImpl#getSafetyTactics <em>Safety Tactics</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SafetyTacticViewpointImpl extends SafetyViewpointImpl implements SafetyTacticViewpoint
{
  /**
   * The cached value of the '{@link #getSafetyTactics() <em>Safety Tactics</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSafetyTactics()
   * @generated
   * @ordered
   */
  protected EList<SafetyTactic> safetyTactics;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SafetyTacticViewpointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SafetyDSLPackage.Literals.SAFETY_TACTIC_VIEWPOINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SafetyTactic> getSafetyTactics()
  {
    if (safetyTactics == null)
    {
      safetyTactics = new EObjectContainmentEList<SafetyTactic>(SafetyTactic.class, this, SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS);
    }
    return safetyTactics;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS:
        return ((InternalEList<?>)getSafetyTactics()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS:
        return getSafetyTactics();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS:
        getSafetyTactics().clear();
        getSafetyTactics().addAll((Collection<? extends SafetyTactic>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS:
        getSafetyTactics().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS:
        return safetyTactics != null && !safetyTactics.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SafetyTacticViewpointImpl
