/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import nl.wur.inf.safetyDSL.ANDNodeExpression;
import nl.wur.inf.safetyDSL.ArchElementToArchElement;
import nl.wur.inf.safetyDSL.ArchitecturalElement;
import nl.wur.inf.safetyDSL.CausedBy;
import nl.wur.inf.safetyDSL.Causes;
import nl.wur.inf.safetyDSL.ClassDef;
import nl.wur.inf.safetyDSL.ClassTestCaseRelation;
import nl.wur.inf.safetyDSL.Commands;
import nl.wur.inf.safetyDSL.Consequence;
import nl.wur.inf.safetyDSL.CriticalityLevel;
import nl.wur.inf.safetyDSL.DerivedFrom;
import nl.wur.inf.safetyDSL.Fault;
import nl.wur.inf.safetyDSL.FaultAvoidance;
import nl.wur.inf.safetyDSL.FaultContainment;
import nl.wur.inf.safetyDSL.FaultDetection;
import nl.wur.inf.safetyDSL.FaultTree;
import nl.wur.inf.safetyDSL.FaultTreeNode;
import nl.wur.inf.safetyDSL.Hazard;
import nl.wur.inf.safetyDSL.HazardElement;
import nl.wur.inf.safetyDSL.HazardRelation;
import nl.wur.inf.safetyDSL.HazardViewpoint;
import nl.wur.inf.safetyDSL.ImplementationDetail;
import nl.wur.inf.safetyDSL.Inits;
import nl.wur.inf.safetyDSL.LevelA;
import nl.wur.inf.safetyDSL.LevelB;
import nl.wur.inf.safetyDSL.LevelC;
import nl.wur.inf.safetyDSL.LevelD;
import nl.wur.inf.safetyDSL.ModuleClassRelation;
import nl.wur.inf.safetyDSL.Monitor;
import nl.wur.inf.safetyDSL.MonitorToArchitecturalElement;
import nl.wur.inf.safetyDSL.Monitors;
import nl.wur.inf.safetyDSL.NonSafetyCritical;
import nl.wur.inf.safetyDSL.ORNodeExpression;
import nl.wur.inf.safetyDSL.Reads;
import nl.wur.inf.safetyDSL.ReportsFault;
import nl.wur.inf.safetyDSL.Restarts;
import nl.wur.inf.safetyDSL.SafeState;
import nl.wur.inf.safetyDSL.SafetyCritical;
import nl.wur.inf.safetyDSL.SafetyCriticalRelation;
import nl.wur.inf.safetyDSL.SafetyCriticalViewpoint;
import nl.wur.inf.safetyDSL.SafetyDSLFactory;
import nl.wur.inf.safetyDSL.SafetyDSLPackage;
import nl.wur.inf.safetyDSL.SafetyFramework;
import nl.wur.inf.safetyDSL.SafetyRequirement;
import nl.wur.inf.safetyDSL.SafetyTactic;
import nl.wur.inf.safetyDSL.SafetyTacticViewpoint;
import nl.wur.inf.safetyDSL.SafetyViewpoint;
import nl.wur.inf.safetyDSL.Starts;
import nl.wur.inf.safetyDSL.State;
import nl.wur.inf.safetyDSL.Stops;
import nl.wur.inf.safetyDSL.Writes;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SafetyDSLPackageImpl extends EPackageImpl implements SafetyDSLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyFrameworkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyViewpointEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass hazardViewpointEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass hazardElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass hazardEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyRequirementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass consequenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faultTreeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faultTreeNodeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass hazardRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass derivedFromEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass causesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass causedByEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyTacticViewpointEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyTacticEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faultAvoidanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faultDetectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faultContainmentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyCriticalViewpointEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass architecturalElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyCriticalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass criticalityLevelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nonSafetyCriticalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass monitorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safetyCriticalRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass archElementToArchElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass monitorToArchitecturalElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass reportsFaultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass implementationDetailEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moduleClassRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass classTestCaseRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass classDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass orNodeExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass andNodeExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass levelAEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass levelBEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass levelCEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass levelDEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass safeStateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass readsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass writesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commandsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stopsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass startsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass restartsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass monitorsEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private SafetyDSLPackageImpl()
  {
    super(eNS_URI, SafetyDSLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link SafetyDSLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static SafetyDSLPackage init()
  {
    if (isInited) return (SafetyDSLPackage)EPackage.Registry.INSTANCE.getEPackage(SafetyDSLPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredSafetyDSLPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    SafetyDSLPackageImpl theSafetyDSLPackage = registeredSafetyDSLPackage instanceof SafetyDSLPackageImpl ? (SafetyDSLPackageImpl)registeredSafetyDSLPackage : new SafetyDSLPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theSafetyDSLPackage.createPackageContents();

    // Initialize created meta-data
    theSafetyDSLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theSafetyDSLPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(SafetyDSLPackage.eNS_URI, theSafetyDSLPackage);
    return theSafetyDSLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyFramework()
  {
    return safetyFrameworkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyFramework_Views()
  {
    return (EReference)safetyFrameworkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyFramework_Detail()
  {
    return (EReference)safetyFrameworkEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyViewpoint()
  {
    return safetyViewpointEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSafetyViewpoint_Name()
  {
    return (EAttribute)safetyViewpointEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHazardViewpoint()
  {
    return hazardViewpointEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getHazardViewpoint_Elements()
  {
    return (EReference)hazardViewpointEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getHazardViewpoint_Relations()
  {
    return (EReference)hazardViewpointEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHazardElement()
  {
    return hazardElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getHazardElement_Name()
  {
    return (EAttribute)hazardElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHazard()
  {
    return hazardEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyRequirement()
  {
    return safetyRequirementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyRequirement_Subrequirements()
  {
    return (EReference)safetyRequirementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConsequence()
  {
    return consequenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFault()
  {
    return faultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFaultTree()
  {
    return faultTreeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFaultTree_RootNode()
  {
    return (EReference)faultTreeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFaultTreeNode()
  {
    return faultTreeNodeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFaultTreeNode_Value()
  {
    return (EReference)faultTreeNodeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFaultTreeNode_Left()
  {
    return (EReference)faultTreeNodeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFaultTreeNode_Right()
  {
    return (EReference)faultTreeNodeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHazardRelation()
  {
    return hazardRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getHazardRelation_Hazard()
  {
    return (EReference)hazardRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDerivedFrom()
  {
    return derivedFromEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDerivedFrom_SafetyRequirements()
  {
    return (EReference)derivedFromEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCauses()
  {
    return causesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCauses_Consequences()
  {
    return (EReference)causesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCausedBy()
  {
    return causedByEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCausedBy_Fault()
  {
    return (EReference)causedByEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyTacticViewpoint()
  {
    return safetyTacticViewpointEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyTacticViewpoint_SafetyTactics()
  {
    return (EReference)safetyTacticViewpointEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyTactic()
  {
    return safetyTacticEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSafetyTactic_Name()
  {
    return (EAttribute)safetyTacticEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSafetyTactic_Type()
  {
    return (EAttribute)safetyTacticEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyTactic_HandledFaults()
  {
    return (EReference)safetyTacticEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFaultAvoidance()
  {
    return faultAvoidanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFaultDetection()
  {
    return faultDetectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFaultContainment()
  {
    return faultContainmentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyCriticalViewpoint()
  {
    return safetyCriticalViewpointEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCriticalViewpoint_Elements()
  {
    return (EReference)safetyCriticalViewpointEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCriticalViewpoint_Relations()
  {
    return (EReference)safetyCriticalViewpointEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArchitecturalElement()
  {
    return architecturalElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArchitecturalElement_Name()
  {
    return (EAttribute)architecturalElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyCritical()
  {
    return safetyCriticalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCritical_Level()
  {
    return (EReference)safetyCriticalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCritical_ImplementedSafetyRequirements()
  {
    return (EReference)safetyCriticalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCritical_ImplementedTactics()
  {
    return (EReference)safetyCriticalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCritical_Subelements()
  {
    return (EReference)safetyCriticalEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSafetyCritical_States()
  {
    return (EReference)safetyCriticalEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCriticalityLevel()
  {
    return criticalityLevelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNonSafetyCritical()
  {
    return nonSafetyCriticalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNonSafetyCritical_Subelements()
  {
    return (EReference)nonSafetyCriticalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMonitor()
  {
    return monitorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMonitor_ImplementedTactics()
  {
    return (EReference)monitorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getState()
  {
    return stateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getState_Name()
  {
    return (EAttribute)stateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafetyCriticalRelation()
  {
    return safetyCriticalRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArchElementToArchElement()
  {
    return archElementToArchElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchElementToArchElement_Element1()
  {
    return (EReference)archElementToArchElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchElementToArchElement_Element2()
  {
    return (EReference)archElementToArchElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMonitorToArchitecturalElement()
  {
    return monitorToArchitecturalElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMonitorToArchitecturalElement_Monitor()
  {
    return (EReference)monitorToArchitecturalElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMonitorToArchitecturalElement_SafetyCritical()
  {
    return (EReference)monitorToArchitecturalElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReportsFault()
  {
    return reportsFaultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getReportsFault_SafetyCritical1()
  {
    return (EReference)reportsFaultEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getReportsFault_SafetyCritical2()
  {
    return (EReference)reportsFaultEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImplementationDetail()
  {
    return implementationDetailEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImplementationDetail_ModuleClassRelations()
  {
    return (EReference)implementationDetailEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImplementationDetail_ClassTestCaseRelations()
  {
    return (EReference)implementationDetailEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModuleClassRelation()
  {
    return moduleClassRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleClassRelation_Module()
  {
    return (EReference)moduleClassRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleClassRelation_Classes()
  {
    return (EReference)moduleClassRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getClassTestCaseRelation()
  {
    return classTestCaseRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getClassTestCaseRelation_Clazz()
  {
    return (EReference)classTestCaseRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getClassTestCaseRelation_TestCases()
  {
    return (EAttribute)classTestCaseRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getClassDef()
  {
    return classDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getClassDef_Name()
  {
    return (EAttribute)classDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getORNodeExpression()
  {
    return orNodeExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getANDNodeExpression()
  {
    return andNodeExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLevelA()
  {
    return levelAEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLevelB()
  {
    return levelBEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLevelC()
  {
    return levelCEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLevelD()
  {
    return levelDEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSafeState()
  {
    return safeStateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReads()
  {
    return readsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getWrites()
  {
    return writesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommands()
  {
    return commandsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStops()
  {
    return stopsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStarts()
  {
    return startsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInits()
  {
    return initsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRestarts()
  {
    return restartsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMonitors()
  {
    return monitorsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyDSLFactory getSafetyDSLFactory()
  {
    return (SafetyDSLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    safetyFrameworkEClass = createEClass(SAFETY_FRAMEWORK);
    createEReference(safetyFrameworkEClass, SAFETY_FRAMEWORK__VIEWS);
    createEReference(safetyFrameworkEClass, SAFETY_FRAMEWORK__DETAIL);

    safetyViewpointEClass = createEClass(SAFETY_VIEWPOINT);
    createEAttribute(safetyViewpointEClass, SAFETY_VIEWPOINT__NAME);

    hazardViewpointEClass = createEClass(HAZARD_VIEWPOINT);
    createEReference(hazardViewpointEClass, HAZARD_VIEWPOINT__ELEMENTS);
    createEReference(hazardViewpointEClass, HAZARD_VIEWPOINT__RELATIONS);

    hazardElementEClass = createEClass(HAZARD_ELEMENT);
    createEAttribute(hazardElementEClass, HAZARD_ELEMENT__NAME);

    hazardEClass = createEClass(HAZARD);

    safetyRequirementEClass = createEClass(SAFETY_REQUIREMENT);
    createEReference(safetyRequirementEClass, SAFETY_REQUIREMENT__SUBREQUIREMENTS);

    consequenceEClass = createEClass(CONSEQUENCE);

    faultEClass = createEClass(FAULT);

    faultTreeEClass = createEClass(FAULT_TREE);
    createEReference(faultTreeEClass, FAULT_TREE__ROOT_NODE);

    faultTreeNodeEClass = createEClass(FAULT_TREE_NODE);
    createEReference(faultTreeNodeEClass, FAULT_TREE_NODE__VALUE);
    createEReference(faultTreeNodeEClass, FAULT_TREE_NODE__LEFT);
    createEReference(faultTreeNodeEClass, FAULT_TREE_NODE__RIGHT);

    hazardRelationEClass = createEClass(HAZARD_RELATION);
    createEReference(hazardRelationEClass, HAZARD_RELATION__HAZARD);

    derivedFromEClass = createEClass(DERIVED_FROM);
    createEReference(derivedFromEClass, DERIVED_FROM__SAFETY_REQUIREMENTS);

    causesEClass = createEClass(CAUSES);
    createEReference(causesEClass, CAUSES__CONSEQUENCES);

    causedByEClass = createEClass(CAUSED_BY);
    createEReference(causedByEClass, CAUSED_BY__FAULT);

    safetyTacticViewpointEClass = createEClass(SAFETY_TACTIC_VIEWPOINT);
    createEReference(safetyTacticViewpointEClass, SAFETY_TACTIC_VIEWPOINT__SAFETY_TACTICS);

    safetyTacticEClass = createEClass(SAFETY_TACTIC);
    createEAttribute(safetyTacticEClass, SAFETY_TACTIC__NAME);
    createEAttribute(safetyTacticEClass, SAFETY_TACTIC__TYPE);
    createEReference(safetyTacticEClass, SAFETY_TACTIC__HANDLED_FAULTS);

    faultAvoidanceEClass = createEClass(FAULT_AVOIDANCE);

    faultDetectionEClass = createEClass(FAULT_DETECTION);

    faultContainmentEClass = createEClass(FAULT_CONTAINMENT);

    safetyCriticalViewpointEClass = createEClass(SAFETY_CRITICAL_VIEWPOINT);
    createEReference(safetyCriticalViewpointEClass, SAFETY_CRITICAL_VIEWPOINT__ELEMENTS);
    createEReference(safetyCriticalViewpointEClass, SAFETY_CRITICAL_VIEWPOINT__RELATIONS);

    architecturalElementEClass = createEClass(ARCHITECTURAL_ELEMENT);
    createEAttribute(architecturalElementEClass, ARCHITECTURAL_ELEMENT__NAME);

    safetyCriticalEClass = createEClass(SAFETY_CRITICAL);
    createEReference(safetyCriticalEClass, SAFETY_CRITICAL__LEVEL);
    createEReference(safetyCriticalEClass, SAFETY_CRITICAL__IMPLEMENTED_SAFETY_REQUIREMENTS);
    createEReference(safetyCriticalEClass, SAFETY_CRITICAL__IMPLEMENTED_TACTICS);
    createEReference(safetyCriticalEClass, SAFETY_CRITICAL__SUBELEMENTS);
    createEReference(safetyCriticalEClass, SAFETY_CRITICAL__STATES);

    criticalityLevelEClass = createEClass(CRITICALITY_LEVEL);

    nonSafetyCriticalEClass = createEClass(NON_SAFETY_CRITICAL);
    createEReference(nonSafetyCriticalEClass, NON_SAFETY_CRITICAL__SUBELEMENTS);

    monitorEClass = createEClass(MONITOR);
    createEReference(monitorEClass, MONITOR__IMPLEMENTED_TACTICS);

    stateEClass = createEClass(STATE);
    createEAttribute(stateEClass, STATE__NAME);

    safetyCriticalRelationEClass = createEClass(SAFETY_CRITICAL_RELATION);

    archElementToArchElementEClass = createEClass(ARCH_ELEMENT_TO_ARCH_ELEMENT);
    createEReference(archElementToArchElementEClass, ARCH_ELEMENT_TO_ARCH_ELEMENT__ELEMENT1);
    createEReference(archElementToArchElementEClass, ARCH_ELEMENT_TO_ARCH_ELEMENT__ELEMENT2);

    monitorToArchitecturalElementEClass = createEClass(MONITOR_TO_ARCHITECTURAL_ELEMENT);
    createEReference(monitorToArchitecturalElementEClass, MONITOR_TO_ARCHITECTURAL_ELEMENT__MONITOR);
    createEReference(monitorToArchitecturalElementEClass, MONITOR_TO_ARCHITECTURAL_ELEMENT__SAFETY_CRITICAL);

    reportsFaultEClass = createEClass(REPORTS_FAULT);
    createEReference(reportsFaultEClass, REPORTS_FAULT__SAFETY_CRITICAL1);
    createEReference(reportsFaultEClass, REPORTS_FAULT__SAFETY_CRITICAL2);

    implementationDetailEClass = createEClass(IMPLEMENTATION_DETAIL);
    createEReference(implementationDetailEClass, IMPLEMENTATION_DETAIL__MODULE_CLASS_RELATIONS);
    createEReference(implementationDetailEClass, IMPLEMENTATION_DETAIL__CLASS_TEST_CASE_RELATIONS);

    moduleClassRelationEClass = createEClass(MODULE_CLASS_RELATION);
    createEReference(moduleClassRelationEClass, MODULE_CLASS_RELATION__MODULE);
    createEReference(moduleClassRelationEClass, MODULE_CLASS_RELATION__CLASSES);

    classTestCaseRelationEClass = createEClass(CLASS_TEST_CASE_RELATION);
    createEReference(classTestCaseRelationEClass, CLASS_TEST_CASE_RELATION__CLAZZ);
    createEAttribute(classTestCaseRelationEClass, CLASS_TEST_CASE_RELATION__TEST_CASES);

    classDefEClass = createEClass(CLASS_DEF);
    createEAttribute(classDefEClass, CLASS_DEF__NAME);

    orNodeExpressionEClass = createEClass(OR_NODE_EXPRESSION);

    andNodeExpressionEClass = createEClass(AND_NODE_EXPRESSION);

    levelAEClass = createEClass(LEVEL_A);

    levelBEClass = createEClass(LEVEL_B);

    levelCEClass = createEClass(LEVEL_C);

    levelDEClass = createEClass(LEVEL_D);

    safeStateEClass = createEClass(SAFE_STATE);

    readsEClass = createEClass(READS);

    writesEClass = createEClass(WRITES);

    commandsEClass = createEClass(COMMANDS);

    stopsEClass = createEClass(STOPS);

    startsEClass = createEClass(STARTS);

    initsEClass = createEClass(INITS);

    restartsEClass = createEClass(RESTARTS);

    monitorsEClass = createEClass(MONITORS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    hazardViewpointEClass.getESuperTypes().add(this.getSafetyViewpoint());
    hazardEClass.getESuperTypes().add(this.getHazardElement());
    safetyRequirementEClass.getESuperTypes().add(this.getHazardElement());
    consequenceEClass.getESuperTypes().add(this.getHazardElement());
    faultEClass.getESuperTypes().add(this.getHazardElement());
    faultTreeEClass.getESuperTypes().add(this.getHazardElement());
    derivedFromEClass.getESuperTypes().add(this.getHazardRelation());
    causesEClass.getESuperTypes().add(this.getHazardRelation());
    causedByEClass.getESuperTypes().add(this.getHazardRelation());
    safetyTacticViewpointEClass.getESuperTypes().add(this.getSafetyViewpoint());
    faultAvoidanceEClass.getESuperTypes().add(this.getSafetyTactic());
    faultDetectionEClass.getESuperTypes().add(this.getSafetyTactic());
    faultContainmentEClass.getESuperTypes().add(this.getSafetyTactic());
    safetyCriticalViewpointEClass.getESuperTypes().add(this.getSafetyViewpoint());
    safetyCriticalEClass.getESuperTypes().add(this.getArchitecturalElement());
    nonSafetyCriticalEClass.getESuperTypes().add(this.getArchitecturalElement());
    monitorEClass.getESuperTypes().add(this.getArchitecturalElement());
    archElementToArchElementEClass.getESuperTypes().add(this.getSafetyCriticalRelation());
    monitorToArchitecturalElementEClass.getESuperTypes().add(this.getSafetyCriticalRelation());
    reportsFaultEClass.getESuperTypes().add(this.getSafetyCriticalRelation());
    orNodeExpressionEClass.getESuperTypes().add(this.getFaultTreeNode());
    andNodeExpressionEClass.getESuperTypes().add(this.getFaultTreeNode());
    levelAEClass.getESuperTypes().add(this.getCriticalityLevel());
    levelBEClass.getESuperTypes().add(this.getCriticalityLevel());
    levelCEClass.getESuperTypes().add(this.getCriticalityLevel());
    levelDEClass.getESuperTypes().add(this.getCriticalityLevel());
    safeStateEClass.getESuperTypes().add(this.getState());
    readsEClass.getESuperTypes().add(this.getArchElementToArchElement());
    writesEClass.getESuperTypes().add(this.getArchElementToArchElement());
    commandsEClass.getESuperTypes().add(this.getArchElementToArchElement());
    stopsEClass.getESuperTypes().add(this.getMonitorToArchitecturalElement());
    startsEClass.getESuperTypes().add(this.getMonitorToArchitecturalElement());
    initsEClass.getESuperTypes().add(this.getMonitorToArchitecturalElement());
    restartsEClass.getESuperTypes().add(this.getMonitorToArchitecturalElement());
    monitorsEClass.getESuperTypes().add(this.getMonitorToArchitecturalElement());

    // Initialize classes and features; add operations and parameters
    initEClass(safetyFrameworkEClass, SafetyFramework.class, "SafetyFramework", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSafetyFramework_Views(), this.getSafetyViewpoint(), null, "views", null, 0, -1, SafetyFramework.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyFramework_Detail(), this.getImplementationDetail(), null, "detail", null, 0, 1, SafetyFramework.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(safetyViewpointEClass, SafetyViewpoint.class, "SafetyViewpoint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSafetyViewpoint_Name(), ecorePackage.getEString(), "name", null, 0, 1, SafetyViewpoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(hazardViewpointEClass, HazardViewpoint.class, "HazardViewpoint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHazardViewpoint_Elements(), this.getHazardElement(), null, "elements", null, 0, -1, HazardViewpoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getHazardViewpoint_Relations(), this.getHazardRelation(), null, "relations", null, 0, -1, HazardViewpoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(hazardElementEClass, HazardElement.class, "HazardElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getHazardElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, HazardElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(hazardEClass, Hazard.class, "Hazard", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(safetyRequirementEClass, SafetyRequirement.class, "SafetyRequirement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSafetyRequirement_Subrequirements(), this.getSafetyRequirement(), null, "subrequirements", null, 0, -1, SafetyRequirement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(consequenceEClass, Consequence.class, "Consequence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(faultEClass, Fault.class, "Fault", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(faultTreeEClass, FaultTree.class, "FaultTree", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFaultTree_RootNode(), this.getFaultTreeNode(), null, "rootNode", null, 0, 1, FaultTree.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(faultTreeNodeEClass, FaultTreeNode.class, "FaultTreeNode", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFaultTreeNode_Value(), this.getFault(), null, "value", null, 0, 1, FaultTreeNode.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFaultTreeNode_Left(), this.getFaultTreeNode(), null, "left", null, 0, 1, FaultTreeNode.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFaultTreeNode_Right(), this.getFaultTreeNode(), null, "right", null, 0, 1, FaultTreeNode.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(hazardRelationEClass, HazardRelation.class, "HazardRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHazardRelation_Hazard(), this.getHazard(), null, "hazard", null, 0, 1, HazardRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(derivedFromEClass, DerivedFrom.class, "DerivedFrom", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDerivedFrom_SafetyRequirements(), this.getSafetyRequirement(), null, "safetyRequirements", null, 0, -1, DerivedFrom.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(causesEClass, Causes.class, "Causes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCauses_Consequences(), this.getConsequence(), null, "consequences", null, 0, -1, Causes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(causedByEClass, CausedBy.class, "CausedBy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCausedBy_Fault(), this.getFaultTree(), null, "fault", null, 0, 1, CausedBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(safetyTacticViewpointEClass, SafetyTacticViewpoint.class, "SafetyTacticViewpoint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSafetyTacticViewpoint_SafetyTactics(), this.getSafetyTactic(), null, "safetyTactics", null, 0, -1, SafetyTacticViewpoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(safetyTacticEClass, SafetyTactic.class, "SafetyTactic", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSafetyTactic_Name(), ecorePackage.getEString(), "name", null, 0, 1, SafetyTactic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSafetyTactic_Type(), ecorePackage.getEString(), "type", null, 0, 1, SafetyTactic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyTactic_HandledFaults(), this.getFault(), null, "handledFaults", null, 0, -1, SafetyTactic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(faultAvoidanceEClass, FaultAvoidance.class, "FaultAvoidance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(faultDetectionEClass, FaultDetection.class, "FaultDetection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(faultContainmentEClass, FaultContainment.class, "FaultContainment", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(safetyCriticalViewpointEClass, SafetyCriticalViewpoint.class, "SafetyCriticalViewpoint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSafetyCriticalViewpoint_Elements(), this.getArchitecturalElement(), null, "elements", null, 0, -1, SafetyCriticalViewpoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyCriticalViewpoint_Relations(), this.getSafetyCriticalRelation(), null, "relations", null, 0, -1, SafetyCriticalViewpoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(architecturalElementEClass, ArchitecturalElement.class, "ArchitecturalElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getArchitecturalElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, ArchitecturalElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(safetyCriticalEClass, SafetyCritical.class, "SafetyCritical", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSafetyCritical_Level(), this.getCriticalityLevel(), null, "level", null, 0, 1, SafetyCritical.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyCritical_ImplementedSafetyRequirements(), this.getSafetyRequirement(), null, "implementedSafetyRequirements", null, 0, -1, SafetyCritical.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyCritical_ImplementedTactics(), this.getSafetyTactic(), null, "implementedTactics", null, 0, -1, SafetyCritical.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyCritical_Subelements(), this.getSafetyCritical(), null, "subelements", null, 0, -1, SafetyCritical.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSafetyCritical_States(), this.getState(), null, "states", null, 0, -1, SafetyCritical.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(criticalityLevelEClass, CriticalityLevel.class, "CriticalityLevel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(nonSafetyCriticalEClass, NonSafetyCritical.class, "NonSafetyCritical", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNonSafetyCritical_Subelements(), this.getNonSafetyCritical(), null, "subelements", null, 0, -1, NonSafetyCritical.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(monitorEClass, Monitor.class, "Monitor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMonitor_ImplementedTactics(), this.getSafetyTactic(), null, "implementedTactics", null, 0, -1, Monitor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stateEClass, State.class, "State", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getState_Name(), ecorePackage.getEString(), "name", null, 0, 1, State.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(safetyCriticalRelationEClass, SafetyCriticalRelation.class, "SafetyCriticalRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(archElementToArchElementEClass, ArchElementToArchElement.class, "ArchElementToArchElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArchElementToArchElement_Element1(), this.getArchitecturalElement(), null, "element1", null, 0, 1, ArchElementToArchElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchElementToArchElement_Element2(), this.getArchitecturalElement(), null, "element2", null, 0, -1, ArchElementToArchElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(monitorToArchitecturalElementEClass, MonitorToArchitecturalElement.class, "MonitorToArchitecturalElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMonitorToArchitecturalElement_Monitor(), this.getMonitor(), null, "monitor", null, 0, 1, MonitorToArchitecturalElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMonitorToArchitecturalElement_SafetyCritical(), this.getSafetyCritical(), null, "safetyCritical", null, 0, -1, MonitorToArchitecturalElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(reportsFaultEClass, ReportsFault.class, "ReportsFault", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getReportsFault_SafetyCritical1(), this.getSafetyCritical(), null, "safetyCritical1", null, 0, 1, ReportsFault.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getReportsFault_SafetyCritical2(), this.getSafetyCritical(), null, "safetyCritical2", null, 0, -1, ReportsFault.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(implementationDetailEClass, ImplementationDetail.class, "ImplementationDetail", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImplementationDetail_ModuleClassRelations(), this.getModuleClassRelation(), null, "moduleClassRelations", null, 0, -1, ImplementationDetail.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImplementationDetail_ClassTestCaseRelations(), this.getClassTestCaseRelation(), null, "classTestCaseRelations", null, 0, -1, ImplementationDetail.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moduleClassRelationEClass, ModuleClassRelation.class, "ModuleClassRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModuleClassRelation_Module(), this.getArchitecturalElement(), null, "module", null, 0, 1, ModuleClassRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleClassRelation_Classes(), this.getClassDef(), null, "classes", null, 0, -1, ModuleClassRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(classTestCaseRelationEClass, ClassTestCaseRelation.class, "ClassTestCaseRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getClassTestCaseRelation_Clazz(), this.getClassDef(), null, "clazz", null, 0, 1, ClassTestCaseRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getClassTestCaseRelation_TestCases(), ecorePackage.getEString(), "testCases", null, 0, -1, ClassTestCaseRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(classDefEClass, ClassDef.class, "ClassDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getClassDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, ClassDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(orNodeExpressionEClass, ORNodeExpression.class, "ORNodeExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(andNodeExpressionEClass, ANDNodeExpression.class, "ANDNodeExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(levelAEClass, LevelA.class, "LevelA", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(levelBEClass, LevelB.class, "LevelB", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(levelCEClass, LevelC.class, "LevelC", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(levelDEClass, LevelD.class, "LevelD", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(safeStateEClass, SafeState.class, "SafeState", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(readsEClass, Reads.class, "Reads", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(writesEClass, Writes.class, "Writes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(commandsEClass, Commands.class, "Commands", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stopsEClass, Stops.class, "Stops", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(startsEClass, Starts.class, "Starts", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(initsEClass, Inits.class, "Inits", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(restartsEClass, Restarts.class, "Restarts", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(monitorsEClass, Monitors.class, "Monitors", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);
  }

} //SafetyDSLPackageImpl
