/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import java.util.Collection;

import nl.wur.inf.safetyDSL.ImplementationDetail;
import nl.wur.inf.safetyDSL.SafetyDSLPackage;
import nl.wur.inf.safetyDSL.SafetyFramework;
import nl.wur.inf.safetyDSL.SafetyViewpoint;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Safety Framework</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.impl.SafetyFrameworkImpl#getViews <em>Views</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.impl.SafetyFrameworkImpl#getDetail <em>Detail</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SafetyFrameworkImpl extends MinimalEObjectImpl.Container implements SafetyFramework
{
  /**
   * The cached value of the '{@link #getViews() <em>Views</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getViews()
   * @generated
   * @ordered
   */
  protected EList<SafetyViewpoint> views;

  /**
   * The cached value of the '{@link #getDetail() <em>Detail</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDetail()
   * @generated
   * @ordered
   */
  protected ImplementationDetail detail;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SafetyFrameworkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SafetyDSLPackage.Literals.SAFETY_FRAMEWORK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SafetyViewpoint> getViews()
  {
    if (views == null)
    {
      views = new EObjectContainmentEList<SafetyViewpoint>(SafetyViewpoint.class, this, SafetyDSLPackage.SAFETY_FRAMEWORK__VIEWS);
    }
    return views;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImplementationDetail getDetail()
  {
    return detail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDetail(ImplementationDetail newDetail, NotificationChain msgs)
  {
    ImplementationDetail oldDetail = detail;
    detail = newDetail;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL, oldDetail, newDetail);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDetail(ImplementationDetail newDetail)
  {
    if (newDetail != detail)
    {
      NotificationChain msgs = null;
      if (detail != null)
        msgs = ((InternalEObject)detail).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL, null, msgs);
      if (newDetail != null)
        msgs = ((InternalEObject)newDetail).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL, null, msgs);
      msgs = basicSetDetail(newDetail, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL, newDetail, newDetail));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_FRAMEWORK__VIEWS:
        return ((InternalEList<?>)getViews()).basicRemove(otherEnd, msgs);
      case SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL:
        return basicSetDetail(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_FRAMEWORK__VIEWS:
        return getViews();
      case SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL:
        return getDetail();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_FRAMEWORK__VIEWS:
        getViews().clear();
        getViews().addAll((Collection<? extends SafetyViewpoint>)newValue);
        return;
      case SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL:
        setDetail((ImplementationDetail)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_FRAMEWORK__VIEWS:
        getViews().clear();
        return;
      case SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL:
        setDetail((ImplementationDetail)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SafetyDSLPackage.SAFETY_FRAMEWORK__VIEWS:
        return views != null && !views.isEmpty();
      case SafetyDSLPackage.SAFETY_FRAMEWORK__DETAIL:
        return detail != null;
    }
    return super.eIsSet(featureID);
  }

} //SafetyFrameworkImpl
