/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import nl.wur.inf.safetyDSL.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SafetyDSLFactoryImpl extends EFactoryImpl implements SafetyDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static SafetyDSLFactory init()
  {
    try
    {
      SafetyDSLFactory theSafetyDSLFactory = (SafetyDSLFactory)EPackage.Registry.INSTANCE.getEFactory(SafetyDSLPackage.eNS_URI);
      if (theSafetyDSLFactory != null)
      {
        return theSafetyDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new SafetyDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SafetyDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case SafetyDSLPackage.SAFETY_FRAMEWORK: return createSafetyFramework();
      case SafetyDSLPackage.SAFETY_VIEWPOINT: return createSafetyViewpoint();
      case SafetyDSLPackage.HAZARD_VIEWPOINT: return createHazardViewpoint();
      case SafetyDSLPackage.HAZARD_ELEMENT: return createHazardElement();
      case SafetyDSLPackage.HAZARD: return createHazard();
      case SafetyDSLPackage.SAFETY_REQUIREMENT: return createSafetyRequirement();
      case SafetyDSLPackage.CONSEQUENCE: return createConsequence();
      case SafetyDSLPackage.FAULT: return createFault();
      case SafetyDSLPackage.FAULT_TREE: return createFaultTree();
      case SafetyDSLPackage.FAULT_TREE_NODE: return createFaultTreeNode();
      case SafetyDSLPackage.HAZARD_RELATION: return createHazardRelation();
      case SafetyDSLPackage.DERIVED_FROM: return createDerivedFrom();
      case SafetyDSLPackage.CAUSES: return createCauses();
      case SafetyDSLPackage.CAUSED_BY: return createCausedBy();
      case SafetyDSLPackage.SAFETY_TACTIC_VIEWPOINT: return createSafetyTacticViewpoint();
      case SafetyDSLPackage.SAFETY_TACTIC: return createSafetyTactic();
      case SafetyDSLPackage.FAULT_AVOIDANCE: return createFaultAvoidance();
      case SafetyDSLPackage.FAULT_DETECTION: return createFaultDetection();
      case SafetyDSLPackage.FAULT_CONTAINMENT: return createFaultContainment();
      case SafetyDSLPackage.SAFETY_CRITICAL_VIEWPOINT: return createSafetyCriticalViewpoint();
      case SafetyDSLPackage.ARCHITECTURAL_ELEMENT: return createArchitecturalElement();
      case SafetyDSLPackage.SAFETY_CRITICAL: return createSafetyCritical();
      case SafetyDSLPackage.CRITICALITY_LEVEL: return createCriticalityLevel();
      case SafetyDSLPackage.NON_SAFETY_CRITICAL: return createNonSafetyCritical();
      case SafetyDSLPackage.MONITOR: return createMonitor();
      case SafetyDSLPackage.STATE: return createState();
      case SafetyDSLPackage.SAFETY_CRITICAL_RELATION: return createSafetyCriticalRelation();
      case SafetyDSLPackage.ARCH_ELEMENT_TO_ARCH_ELEMENT: return createArchElementToArchElement();
      case SafetyDSLPackage.MONITOR_TO_ARCHITECTURAL_ELEMENT: return createMonitorToArchitecturalElement();
      case SafetyDSLPackage.REPORTS_FAULT: return createReportsFault();
      case SafetyDSLPackage.IMPLEMENTATION_DETAIL: return createImplementationDetail();
      case SafetyDSLPackage.MODULE_CLASS_RELATION: return createModuleClassRelation();
      case SafetyDSLPackage.CLASS_TEST_CASE_RELATION: return createClassTestCaseRelation();
      case SafetyDSLPackage.CLASS_DEF: return createClassDef();
      case SafetyDSLPackage.OR_NODE_EXPRESSION: return createORNodeExpression();
      case SafetyDSLPackage.AND_NODE_EXPRESSION: return createANDNodeExpression();
      case SafetyDSLPackage.LEVEL_A: return createLevelA();
      case SafetyDSLPackage.LEVEL_B: return createLevelB();
      case SafetyDSLPackage.LEVEL_C: return createLevelC();
      case SafetyDSLPackage.LEVEL_D: return createLevelD();
      case SafetyDSLPackage.SAFE_STATE: return createSafeState();
      case SafetyDSLPackage.READS: return createReads();
      case SafetyDSLPackage.WRITES: return createWrites();
      case SafetyDSLPackage.COMMANDS: return createCommands();
      case SafetyDSLPackage.STOPS: return createStops();
      case SafetyDSLPackage.STARTS: return createStarts();
      case SafetyDSLPackage.INITS: return createInits();
      case SafetyDSLPackage.RESTARTS: return createRestarts();
      case SafetyDSLPackage.MONITORS: return createMonitors();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyFramework createSafetyFramework()
  {
    SafetyFrameworkImpl safetyFramework = new SafetyFrameworkImpl();
    return safetyFramework;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyViewpoint createSafetyViewpoint()
  {
    SafetyViewpointImpl safetyViewpoint = new SafetyViewpointImpl();
    return safetyViewpoint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HazardViewpoint createHazardViewpoint()
  {
    HazardViewpointImpl hazardViewpoint = new HazardViewpointImpl();
    return hazardViewpoint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HazardElement createHazardElement()
  {
    HazardElementImpl hazardElement = new HazardElementImpl();
    return hazardElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Hazard createHazard()
  {
    HazardImpl hazard = new HazardImpl();
    return hazard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyRequirement createSafetyRequirement()
  {
    SafetyRequirementImpl safetyRequirement = new SafetyRequirementImpl();
    return safetyRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Consequence createConsequence()
  {
    ConsequenceImpl consequence = new ConsequenceImpl();
    return consequence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fault createFault()
  {
    FaultImpl fault = new FaultImpl();
    return fault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FaultTree createFaultTree()
  {
    FaultTreeImpl faultTree = new FaultTreeImpl();
    return faultTree;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FaultTreeNode createFaultTreeNode()
  {
    FaultTreeNodeImpl faultTreeNode = new FaultTreeNodeImpl();
    return faultTreeNode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HazardRelation createHazardRelation()
  {
    HazardRelationImpl hazardRelation = new HazardRelationImpl();
    return hazardRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DerivedFrom createDerivedFrom()
  {
    DerivedFromImpl derivedFrom = new DerivedFromImpl();
    return derivedFrom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Causes createCauses()
  {
    CausesImpl causes = new CausesImpl();
    return causes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CausedBy createCausedBy()
  {
    CausedByImpl causedBy = new CausedByImpl();
    return causedBy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyTacticViewpoint createSafetyTacticViewpoint()
  {
    SafetyTacticViewpointImpl safetyTacticViewpoint = new SafetyTacticViewpointImpl();
    return safetyTacticViewpoint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyTactic createSafetyTactic()
  {
    SafetyTacticImpl safetyTactic = new SafetyTacticImpl();
    return safetyTactic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FaultAvoidance createFaultAvoidance()
  {
    FaultAvoidanceImpl faultAvoidance = new FaultAvoidanceImpl();
    return faultAvoidance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FaultDetection createFaultDetection()
  {
    FaultDetectionImpl faultDetection = new FaultDetectionImpl();
    return faultDetection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FaultContainment createFaultContainment()
  {
    FaultContainmentImpl faultContainment = new FaultContainmentImpl();
    return faultContainment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyCriticalViewpoint createSafetyCriticalViewpoint()
  {
    SafetyCriticalViewpointImpl safetyCriticalViewpoint = new SafetyCriticalViewpointImpl();
    return safetyCriticalViewpoint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArchitecturalElement createArchitecturalElement()
  {
    ArchitecturalElementImpl architecturalElement = new ArchitecturalElementImpl();
    return architecturalElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyCritical createSafetyCritical()
  {
    SafetyCriticalImpl safetyCritical = new SafetyCriticalImpl();
    return safetyCritical;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CriticalityLevel createCriticalityLevel()
  {
    CriticalityLevelImpl criticalityLevel = new CriticalityLevelImpl();
    return criticalityLevel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NonSafetyCritical createNonSafetyCritical()
  {
    NonSafetyCriticalImpl nonSafetyCritical = new NonSafetyCriticalImpl();
    return nonSafetyCritical;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Monitor createMonitor()
  {
    MonitorImpl monitor = new MonitorImpl();
    return monitor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public State createState()
  {
    StateImpl state = new StateImpl();
    return state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyCriticalRelation createSafetyCriticalRelation()
  {
    SafetyCriticalRelationImpl safetyCriticalRelation = new SafetyCriticalRelationImpl();
    return safetyCriticalRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArchElementToArchElement createArchElementToArchElement()
  {
    ArchElementToArchElementImpl archElementToArchElement = new ArchElementToArchElementImpl();
    return archElementToArchElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MonitorToArchitecturalElement createMonitorToArchitecturalElement()
  {
    MonitorToArchitecturalElementImpl monitorToArchitecturalElement = new MonitorToArchitecturalElementImpl();
    return monitorToArchitecturalElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReportsFault createReportsFault()
  {
    ReportsFaultImpl reportsFault = new ReportsFaultImpl();
    return reportsFault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImplementationDetail createImplementationDetail()
  {
    ImplementationDetailImpl implementationDetail = new ImplementationDetailImpl();
    return implementationDetail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ModuleClassRelation createModuleClassRelation()
  {
    ModuleClassRelationImpl moduleClassRelation = new ModuleClassRelationImpl();
    return moduleClassRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassTestCaseRelation createClassTestCaseRelation()
  {
    ClassTestCaseRelationImpl classTestCaseRelation = new ClassTestCaseRelationImpl();
    return classTestCaseRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ClassDef createClassDef()
  {
    ClassDefImpl classDef = new ClassDefImpl();
    return classDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ORNodeExpression createORNodeExpression()
  {
    ORNodeExpressionImpl orNodeExpression = new ORNodeExpressionImpl();
    return orNodeExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ANDNodeExpression createANDNodeExpression()
  {
    ANDNodeExpressionImpl andNodeExpression = new ANDNodeExpressionImpl();
    return andNodeExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LevelA createLevelA()
  {
    LevelAImpl levelA = new LevelAImpl();
    return levelA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LevelB createLevelB()
  {
    LevelBImpl levelB = new LevelBImpl();
    return levelB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LevelC createLevelC()
  {
    LevelCImpl levelC = new LevelCImpl();
    return levelC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LevelD createLevelD()
  {
    LevelDImpl levelD = new LevelDImpl();
    return levelD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafeState createSafeState()
  {
    SafeStateImpl safeState = new SafeStateImpl();
    return safeState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reads createReads()
  {
    ReadsImpl reads = new ReadsImpl();
    return reads;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Writes createWrites()
  {
    WritesImpl writes = new WritesImpl();
    return writes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Commands createCommands()
  {
    CommandsImpl commands = new CommandsImpl();
    return commands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Stops createStops()
  {
    StopsImpl stops = new StopsImpl();
    return stops;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Starts createStarts()
  {
    StartsImpl starts = new StartsImpl();
    return starts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Inits createInits()
  {
    InitsImpl inits = new InitsImpl();
    return inits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Restarts createRestarts()
  {
    RestartsImpl restarts = new RestartsImpl();
    return restarts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Monitors createMonitors()
  {
    MonitorsImpl monitors = new MonitorsImpl();
    return monitors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SafetyDSLPackage getSafetyDSLPackage()
  {
    return (SafetyDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static SafetyDSLPackage getPackage()
  {
    return SafetyDSLPackage.eINSTANCE;
  }

} //SafetyDSLFactoryImpl
