/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL.impl;

import nl.wur.inf.safetyDSL.SafetyDSLPackage;
import nl.wur.inf.safetyDSL.Starts;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Starts</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StartsImpl extends MonitorToArchitecturalElementImpl implements Starts
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StartsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SafetyDSLPackage.Literals.STARTS;
  }

} //StartsImpl
