/*
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SafetyDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/wur/inf/parser/antlr/internal/InternalSafetyDSL.tokens");
	}
}
