/*
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.ide

import com.google.inject.Guice
import nl.wur.inf.SafetyDSLRuntimeModule
import nl.wur.inf.SafetyDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SafetyDSLIdeSetup extends SafetyDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SafetyDSLRuntimeModule, new SafetyDSLIdeModule))
	}
	
}
