/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AND Node Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getANDNodeExpression()
 * @model
 * @generated
 */
public interface ANDNodeExpression extends FaultTreeNode
{
} // ANDNodeExpression
