/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Criticality Level</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getCriticalityLevel()
 * @model
 * @generated
 */
public interface CriticalityLevel extends EObject
{
} // CriticalityLevel
