/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fault Avoidance</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getFaultAvoidance()
 * @model
 * @generated
 */
public interface FaultAvoidance extends SafetyTactic
{
} // FaultAvoidance
