/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fault Tree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.FaultTree#getRootNode <em>Root Node</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getFaultTree()
 * @model
 * @generated
 */
public interface FaultTree extends HazardElement
{
  /**
   * Returns the value of the '<em><b>Root Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root Node</em>' containment reference.
   * @see #setRootNode(FaultTreeNode)
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getFaultTree_RootNode()
   * @model containment="true"
   * @generated
   */
  FaultTreeNode getRootNode();

  /**
   * Sets the value of the '{@link nl.wur.inf.safetyDSL.FaultTree#getRootNode <em>Root Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root Node</em>' containment reference.
   * @see #getRootNode()
   * @generated
   */
  void setRootNode(FaultTreeNode value);

} // FaultTree
