/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fault Detection</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getFaultDetection()
 * @model
 * @generated
 */
public interface FaultDetection extends SafetyTactic
{
} // FaultDetection
