/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hazard Viewpoint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.HazardViewpoint#getElements <em>Elements</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.HazardViewpoint#getRelations <em>Relations</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getHazardViewpoint()
 * @model
 * @generated
 */
public interface HazardViewpoint extends SafetyViewpoint
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.HazardElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getHazardViewpoint_Elements()
   * @model containment="true"
   * @generated
   */
  EList<HazardElement> getElements();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.HazardRelation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getHazardViewpoint_Relations()
   * @model containment="true"
   * @generated
   */
  EList<HazardRelation> getRelations();

} // HazardViewpoint
