/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hazard Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.HazardRelation#getHazard <em>Hazard</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getHazardRelation()
 * @model
 * @generated
 */
public interface HazardRelation extends EObject
{
  /**
   * Returns the value of the '<em><b>Hazard</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hazard</em>' reference.
   * @see #setHazard(Hazard)
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getHazardRelation_Hazard()
   * @model
   * @generated
   */
  Hazard getHazard();

  /**
   * Sets the value of the '{@link nl.wur.inf.safetyDSL.HazardRelation#getHazard <em>Hazard</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hazard</em>' reference.
   * @see #getHazard()
   * @generated
   */
  void setHazard(Hazard value);

} // HazardRelation
