/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Implementation Detail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.ImplementationDetail#getModuleClassRelations <em>Module Class Relations</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.ImplementationDetail#getClassTestCaseRelations <em>Class Test Case Relations</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getImplementationDetail()
 * @model
 * @generated
 */
public interface ImplementationDetail extends EObject
{
  /**
   * Returns the value of the '<em><b>Module Class Relations</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.ModuleClassRelation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module Class Relations</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getImplementationDetail_ModuleClassRelations()
   * @model containment="true"
   * @generated
   */
  EList<ModuleClassRelation> getModuleClassRelations();

  /**
   * Returns the value of the '<em><b>Class Test Case Relations</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.ClassTestCaseRelation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Test Case Relations</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getImplementationDetail_ClassTestCaseRelations()
   * @model containment="true"
   * @generated
   */
  EList<ClassTestCaseRelation> getClassTestCaseRelations();

} // ImplementationDetail
