/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Level C</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getLevelC()
 * @model
 * @generated
 */
public interface LevelC extends CriticalityLevel
{
} // LevelC
