/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Class Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.ModuleClassRelation#getModule <em>Module</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.ModuleClassRelation#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getModuleClassRelation()
 * @model
 * @generated
 */
public interface ModuleClassRelation extends EObject
{
  /**
   * Returns the value of the '<em><b>Module</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module</em>' reference.
   * @see #setModule(ArchitecturalElement)
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getModuleClassRelation_Module()
   * @model
   * @generated
   */
  ArchitecturalElement getModule();

  /**
   * Sets the value of the '{@link nl.wur.inf.safetyDSL.ModuleClassRelation#getModule <em>Module</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module</em>' reference.
   * @see #getModule()
   * @generated
   */
  void setModule(ArchitecturalElement value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.ClassDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getModuleClassRelation_Classes()
   * @model containment="true"
   * @generated
   */
  EList<ClassDef> getClasses();

} // ModuleClassRelation
