/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monitor To Architectural Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.MonitorToArchitecturalElement#getMonitor <em>Monitor</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.MonitorToArchitecturalElement#getSafetyCritical <em>Safety Critical</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getMonitorToArchitecturalElement()
 * @model
 * @generated
 */
public interface MonitorToArchitecturalElement extends SafetyCriticalRelation
{
  /**
   * Returns the value of the '<em><b>Monitor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monitor</em>' reference.
   * @see #setMonitor(Monitor)
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getMonitorToArchitecturalElement_Monitor()
   * @model
   * @generated
   */
  Monitor getMonitor();

  /**
   * Sets the value of the '{@link nl.wur.inf.safetyDSL.MonitorToArchitecturalElement#getMonitor <em>Monitor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monitor</em>' reference.
   * @see #getMonitor()
   * @generated
   */
  void setMonitor(Monitor value);

  /**
   * Returns the value of the '<em><b>Safety Critical</b></em>' reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.SafetyCritical}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Safety Critical</em>' reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getMonitorToArchitecturalElement_SafetyCritical()
   * @model
   * @generated
   */
  EList<SafetyCritical> getSafetyCritical();

} // MonitorToArchitecturalElement
