/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Safety Framework</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.SafetyFramework#getViews <em>Views</em>}</li>
 *   <li>{@link nl.wur.inf.safetyDSL.SafetyFramework#getDetail <em>Detail</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getSafetyFramework()
 * @model
 * @generated
 */
public interface SafetyFramework extends EObject
{
  /**
   * Returns the value of the '<em><b>Views</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.SafetyViewpoint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Views</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getSafetyFramework_Views()
   * @model containment="true"
   * @generated
   */
  EList<SafetyViewpoint> getViews();

  /**
   * Returns the value of the '<em><b>Detail</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Detail</em>' containment reference.
   * @see #setDetail(ImplementationDetail)
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getSafetyFramework_Detail()
   * @model containment="true"
   * @generated
   */
  ImplementationDetail getDetail();

  /**
   * Sets the value of the '{@link nl.wur.inf.safetyDSL.SafetyFramework#getDetail <em>Detail</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Detail</em>' containment reference.
   * @see #getDetail()
   * @generated
   */
  void setDetail(ImplementationDetail value);

} // SafetyFramework
