/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Safety Critical Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getSafetyCriticalRelation()
 * @model
 * @generated
 */
public interface SafetyCriticalRelation extends EObject
{
} // SafetyCriticalRelation
