/**
 * generated by Xtext 2.18.0
 */
package nl.wur.inf.safetyDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Safety Tactic Viewpoint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.wur.inf.safetyDSL.SafetyTacticViewpoint#getSafetyTactics <em>Safety Tactics</em>}</li>
 * </ul>
 *
 * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getSafetyTacticViewpoint()
 * @model
 * @generated
 */
public interface SafetyTacticViewpoint extends SafetyViewpoint
{
  /**
   * Returns the value of the '<em><b>Safety Tactics</b></em>' containment reference list.
   * The list contents are of type {@link nl.wur.inf.safetyDSL.SafetyTactic}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Safety Tactics</em>' containment reference list.
   * @see nl.wur.inf.safetyDSL.SafetyDSLPackage#getSafetyTacticViewpoint_SafetyTactics()
   * @model containment="true"
   * @generated
   */
  EList<SafetyTactic> getSafetyTactics();

} // SafetyTacticViewpoint
